package com.media.notabadplayer.Controls;

public enum ApplicationInput
{
    HOME_BUTTON,
    PLAYER_VOLUME_UP_BUTTON,
    PLAYER_VOLUME_DOWN_BUTTON,
    QUICK_PLAYER_VOLUME_UP_BUTTON,
    QUICK_PLAYER_VOLUME_DOWN_BUTTON,
    SCREEN_LOCK_BUTTON,
    PLAYER_PLAY_BUTTON,
    PLAYER_NEXT_BUTTON,
    PLAYER_PREVIOUS_BUTTON,
    QUICK_PLAYER_PLAY_BUTTON,
    QUICK_PLAYER_NEXT_BUTTON,
    QUICK_PLAYER_PREVIOUS_BUTTON
}
