package com.media.notabadplayer.Controls;

public enum ApplicationAction {
    DO_NOTHING,
    EXIT,
    PLAY,
    PAUSE,
    PAUSE_OR_RESUME,
    NEXT_TRACK,
    PREVIOUS_TRACK,
    SHUFFLE,
    VOLUME_UP,
    VOLUME_DOWN,
    MUTE_OR_UNMUTE,
    JUMP_FORWARDS_5,
    JUMP_FORWARDS_8,
    JUMP_FORWARDS_10,
    JUMP_FORWARDS_15,
    JUMP_BACKWARDS_5,
    JUMP_BACKWARDS_8,
    JUMP_BACKWARDS_10,
    JUMP_BACKWARDS_15,
    CHANGE_PLAY_ORDER,
    PREVIOUS_PLAYED_TRACK
}
