package com.media.notabadplayer.Controls;

public enum ApplicationInput
{
    EARPHONES_UNPLUG,
    EXTERNAL_PLAY,
    PLAYER_VOLUME_UP_BUTTON,
    PLAYER_VOLUME_DOWN_BUTTON,
    PLAYER_RECALL,
    PLAYER_PLAY_BUTTON,
    PLAYER_NEXT_BUTTON,
    PLAYER_PREVIOUS_BUTTON,
    PLAYER_SWIPE_LEFT,
    PLAYER_SWIPE_RIGHT,
    PLAYER_VOLUME,
    QUICK_PLAYER_VOLUME_UP_BUTTON,
    QUICK_PLAYER_VOLUME_DOWN_BUTTON,
    QUICK_PLAYER_PLAY_BUTTON,
    QUICK_PLAYER_NEXT_BUTTON,
    QUICK_PLAYER_PREVIOUS_BUTTON
}
